### ISSUE TITLE
未进行引物设计/Cannot Find Designed Primer

### ISSUE THREAD

**Issue by Antoo5801** [AGIScuipeng/PMPrimer#1]
Hi dear all

When I start command:
pmprimer -f final_out_seqs.fasta 
 I have this error:
未进行引物设计/Cannot Find Designed Primer

**Comment by N3R1UM** [comment]
This is because you skipped the alldesign (-a) module and directly entered the evaluate (-e) module. This issue occurs because the primer design was not completed using the primer2 parameter in the alldesign module. It is recommended to use the primer2 parameter to complete the primer design after confirming the parameters in the alldesign module, and then start the evaluation module.
