### ISSUE TITLE
Enhance File Extension Support: Add support for .afa, and .fa Extensions

### ISSUE THREAD

**Issue by davidyytan** [AGIScuipeng/PMPrimer#5]
### Proposed Change: Enhanced File Extension Handling

In the current implementation, the application processes input files using a fixed file extension, namely `.fasta`. This limitation is addressed in the following code snippet:

piece/piecedesign
class piecedesign():
```python
self.tmpfile_path = self.filepath.replace('.fasta', '.mc.fasta') if self.filepath is not None and '.fasta' in self.filepath else pbase.errorlog('文件路径为空，或命名错误')
```

I propose to improve the system's file extension handling by replacing the fixed string-based replacement with a more versatile regex-based approach. This change will provide flexibility in processing multiple file extensions, including .fasta, .afa, and .fa. The modified code will look as follows:

```python
import re
self.tmpfile_path = re.sub(r"\.fasta|\.afa|\.fa", ".mc.fasta", self.filepath) if self.filepath is not None and '.fasta' in self.filepath else pbase.errorlog('文件路径为空，或命名错误')
```
This enhancement will allow the application to work with a broader range of file extensions, improving its adaptability and user experience.

Your feedback on this proposed change is highly appreciated. Thank you for your consideration!

**Comment by N3R1UM** [comment]
Currently, there are no strict restrictions on file suffixes except for alignment sequences, which may cause other code runtime exceptions. However, I currently do not have time to handle them. I understand your intention, but the position where you modified the code is not correct. The true judgment of that line of code is after `if`, so the `re.sub` function you added will not achieve your goal. If you can modify the code as accurately and concisely as possible to achieve your goals, you can apply for a pull request again. Otherwise, I may add support for other suffixes after a period of time.

**Comment by davidyytan** [comment]
```python
import os
import re
self.tmpfile_path = re.sub(r"\.fasta|\.afa|\.fa", ".mc.fasta", self.filepath) if self.filepath is not None and os.path.splitext(self.filepath)[1] in [ '.fasta', '.afa', '.fa'] else pbase.errorlog('文件路径为空，或命名错误')
```
Updated the logic. Do check again. Thanks!
